version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ACCOUNT_ID: "683627574286"
    REPOSITORY_NAME: "fastapi-lambda"
    LAMBDA_FUNCTION_NAME: "fastapilam"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
      - REPOSITORY_URI=683627574286.dkr.ecr.ap-south-1.amazonaws.com/fastapi-lambda@sha256:320d401b779e08d7f1030a39ef679510e6af3d11b57a8ac46f5da369b8ffd2c0
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Waiting for image to be available in ECR..."
      - sleep 10
      - echo "Updating Lambda function to use latest image..."
      - aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --image-uri $REPOSITORY_URI:latest \
          --region $AWS_DEFAULT_REGION

artifacts:
  files: []

